export const ORDERS_LIST_LOADING = 'ORDERS_LIST_LOADING'; 
export const ADD_ORDERS = 'ADD_ORDERS'; 
export const ADD_DISPLAY_ORDERS = 'ADD_DISPLAY_ORDERS'; 
export const NEXT_DISPLAY_ORDERS = 'NEXT_DISPLAY_ORDERS'; 
export const PREV_DISPLAY_ORDERS = 'PREV_DISPLAY_ORDERS'; 
export const ADD_QUERIED_ORDERS = 'ADD_QUERIED_ORDERS';
export const ORDERS_LIST_FAILED = 'ORDERS_LIST_FAILED'; 